# PlatformIO pre-build hook: stamp the firmware with the git revision by
# generating src/version.h (gitignored). Rewritten only when the hash changes
# so incremental builds stay incremental.

Import("env")  # noqa: F821

import subprocess
from pathlib import Path


def git_describe(project_dir):
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short=8", "HEAD"], cwd=project_dir,
            stderr=subprocess.DEVNULL).decode().strip()
        dirty = subprocess.check_output(
            ["git", "status", "--porcelain"], cwd=project_dir,
            stderr=subprocess.DEVNULL).decode().strip()
        return rev + ("-dirty" if dirty else "")
    except Exception:
        return "unknown"


def write_version():
    project_dir = Path(env["PROJECT_DIR"])  # noqa: F821
    out = project_dir / "src" / "version.h"
    content = (
        "// Generated by scripts/git_version.py - do not edit\n"
        "#ifndef TEG_VERSION_H\n"
        "#define TEG_VERSION_H\n"
        f'#define TEG_GIT_HASH "{git_describe(project_dir)}"\n'
        "#endif\n"
    )
    if not out.exists() or out.read_text() != content:
        out.write_text(content)
        print(f"git_version: {git_describe(project_dir)} -> src/version.h")


write_version()
