# PlatformIO pre-build hook: gzip everything in web/ into src/web_assets.h so
# the firmware can serve the modern UI from flash, gzip-compressed.
# (Careful editing the two lines above: a "word: name" pattern there is read
# as a PEP 263 source-encoding declaration by the Python parser.)
# The header is generated (gitignored); it is only rewritten when the content
# actually changes so incremental builds stay incremental.

Import("env")  # noqa: F821

import gzip
from pathlib import Path

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css",
    ".js": "application/javascript",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".json": "application/json",
}


def build_web_assets():
    project_dir = Path(env["PROJECT_DIR"])  # noqa: F821
    web_dir = project_dir / "web"
    out_path = project_dir / "src" / "web_assets.h"

    if not web_dir.is_dir():
        return

    assets = []
    for f in sorted(web_dir.iterdir()):
        if not f.is_file() or f.suffix not in CONTENT_TYPES:
            continue
        raw = f.read_bytes()
        # mtime=0 keeps the gzip output deterministic across builds
        packed = bytearray(gzip.compress(raw, compresslevel=9, mtime=0))
        # Python versions that delegate mtime=0 to zlib inherit zlib's host OS
        # byte (gzip header offset 9), so Linux and Windows produced different
        # firmware from identical sources. 255 means "unknown" and is canonical.
        packed[9] = 255
        packed = bytes(packed)
        assets.append((f.name, CONTENT_TYPES[f.suffix], packed, len(raw)))

    lines = [
        "// Generated by scripts/gzip_web_assets.py - do not edit, edit web/ instead",
        "#ifndef WEB_ASSETS_H",
        "#define WEB_ASSETS_H",
        "",
        "#include <stdint.h>",
        "",
        "// Teensy's linker copies plain .rodata into DTCM; PROGMEM keeps these",
        "// arrays in (memory-mapped, cached) flash instead.",
        "#ifndef PROGMEM",
        "#define PROGMEM",
        "#endif",
        "",
        "struct WebAsset {",
        "  const char *path;         // request path, e.g. \"/index.html\"",
        "  const char *contentType;",
        "  const uint8_t *data;      // gzip-compressed",
        "  unsigned int length;",
        "};",
        "",
    ]

    for name, ctype, packed, raw_len in assets:
        ident = name.replace(".", "_").replace("-", "_")
        lines.append(
            f"// {name}: {raw_len} bytes raw, {len(packed)} bytes gzipped"
        )
        lines.append(f"static const uint8_t WebAssetData_{ident}[] PROGMEM = {{")
        for i in range(0, len(packed), 20):
            chunk = ",".join(str(b) for b in packed[i : i + 20])
            lines.append(f"  {chunk},")
        lines.append("};")
        lines.append("")

    lines.append("static const WebAsset WebAssets[] = {")
    for name, ctype, packed, _ in assets:
        ident = name.replace(".", "_").replace("-", "_")
        lines.append(
            f'  {{"/{name}", "{ctype}", WebAssetData_{ident}, {len(packed)}}},'
        )
    lines.append("};")
    lines.append(
        "static const unsigned int WebAssetCount = "
        "sizeof(WebAssets) / sizeof(WebAssets[0]);"
    )
    lines.append("")
    lines.append("#endif")
    content = "\n".join(lines) + "\n"

    if not out_path.exists() or out_path.read_text() != content:
        out_path.write_text(content)
        total = sum(len(p) for _, _, p, _ in assets)
        print(
            f"gzip_web_assets: {len(assets)} asset(s), {total} bytes gzipped -> src/web_assets.h"
        )


build_web_assets()
